<template>
    <b-modal v-model="showModal" header-class="p-3" title="Generate BAC Resolution" size="xl" centered no-close-on-backdrop >
        <form class="customform">
           <BRow>
                 <BCol lg="6" class="mt-2">
                    <InputLabel value="BAC Resolution Number"/>
                    <TextInput v-model="form.bac_resolution_number" placeholder="<Autogenerated>"  class="form-control"  :light="true" readonly/>
                </BCol>
                <BCol lg="6" class="mt-2">
                    <InputLabel value="Purchase Request Number"/>
                    <TextInput v-model="data.purchase_request_number"  class="form-control"  :light="true" readonly/>
                </BCol>
                <BCol lg="12" class="mt-2" >
                    <ckeditor v-model="form.body" :editor="editor"></ckeditor>
                </BCol>
            </BRow>
        </form>


          <template v-slot:footer>
            <b-button @click="hide()" variant="light" block>Cancel</b-button>
            <b-button @click="submit()" variant="success"  block>Save</b-button>
        </template>
        
    </b-modal>
</template>
<script>
import { useForm } from '@inertiajs/vue3';
import Multiselect from "@vueform/multiselect";
import InputError from '@/Shared/Components/Forms/InputError.vue';
import InputLabel from '@/Shared/Components/Forms/InputLabel.vue';
import TextInput from '@/Shared/Components/Forms/TextInput.vue';
import CKEditor from '@ckeditor/ckeditor5-vue';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

export default {
    components: { InputError, InputLabel, TextInput, Multiselect, ckeditor: CKEditor.component  },
    props:['bids','data'],
    data(){
        return {
            currentUrl: window.location.origin,
            form: useForm({
                id: null,
                bac_resolution_number: null,
                purchase_request_id: this.data.id,
                body: this.editorData,
            }),
            currentUrl: window.location.origin,        
            showModal: false,
            editor: ClassicEditor,
            editorData: '',
            awardedBids: {},
            submission_not_later_than: null,
            rfq_date: '',
        }
    },

    watch: {
        'submission_not_later_than': function(value) {
            if(value){
                this.rfq_date = this.dateFormat(value);
                this.Content();
            }
        },
        'editorData': function(value) {
            if(value){
                this.form.body = value;
            }
        },
    },


    mounted(){
        this.getDateSubmisionNotLaterThan();
        this.Content();
    },


    methods: { 

        show(){
            this.form.reset();
            this.showModal = true;
        },

        edit(data){
            this.form.id = data.id;
            this.form.bac_resolution_number = data.bac_resolution_number;
            this.form.purchase_request_id = data.purchase_request_id;
            this.form.body = data.body;
            this.showModal = true;
        },

      
        hide(){
            this.form.reset();
            this.showModal = false;
        },

        numberToWords(num) {
            if (num === 0) return "ZERO";

            const ones = ["", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE"];
            const teens = ["ELEVEN", "TWELVE", "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN"];
            const tens = ["", "TEN", "TWENTY", "THIRTY", "FORTY", "FIFTY", "SIXTY", "SEVENTY", "EIGHTY", "NINETY"];
            const thousands = ["", "THOUSAND", "MILLION", "BILLION", "TRILLION"];

            function convertChunk(n) {
                let str = "";
                if (n >= 100) {
                str += ones[Math.floor(n / 100)] + " HUNDRED ";
                n %= 100;
                }
                if (n >= 11 && n <= 19) {
                str += teens[n - 11] + " ";
                return str;
                } else if (n >= 10) {
                str += tens[Math.floor(n / 10)] + " ";
                n %= 10;
                }
                if (n > 0) {
                str += ones[n] + " ";
                }
                return str;
            }

            let word = "";
            let chunkIndex = 0;

            while (num > 0) {
                let chunk = num % 1000;
                if (chunk > 0) {
                word = convertChunk(chunk) + thousands[chunkIndex] + " " + word;
                }
                num = Math.floor(num / 1000);
                chunkIndex++;
            }

            return word.trim();
        },

        getModeOfProcurements() {
            axios.get('/faims/bids',{
                params : {
                    option: 'pr_awarded_bids'
                }
            })
            .then(response => {
                if(response){
                    this.awardedBids = response.data;   
                }
            })
            .catch(err => console.log(err));
        },

        
        getDateSubmisionNotLaterThan() {
            axios.get('/faims/bids',{
                params : {
                    id: this.data.id,
                    option: 'submission_not_later_than'
                }
            })
            .then(response => {
                if(response){
                    this.submission_not_later_than = response.data;   

                }
            })
            .catch(err => console.log(err));
        },

        dateFormat(dateString) {
            
                const date = new Date(dateString);
                const day = date.getDate();
                const month = date.toLocaleString('default', { month: 'long' }); // Full month name (e.g., "February")
                const year = date.getFullYear(); // Get year

                // Function to determine ordinal suffix
                const getOrdinalSuffix = (num) => {
                if (num >= 11 && num <= 13) return "th"; // Special case for 11-13
                const lastDigit = num % 10;
                switch (lastDigit) {
                    case 1: return "st";
                    case 2: return "nd";
                    case 3: return "rd";
                    default: return "th";
                    }
                };

                const ordinalSuffix = getOrdinalSuffix(day);
                return `${day}<sup>${ordinalSuffix}</sup> day of ${month} ${year}`;
           
        },

        getFormattedDate() {
            const date = new Date(); // Get today's date
            const day = date.getDate();
            const month = date.toLocaleString('default', { month: 'long' }); // Full month name (e.g., "February")
            const year = date.getFullYear(); // Get current year

            // Function to determine ordinal suffix
            const getOrdinalSuffix = (num) => {
            if (num >= 11 && num <= 13) return "th"; // Special case for 11-13
            const lastDigit = num % 10;
            switch (lastDigit) {
                case 1: return "st";
                case 2: return "nd";
                case 3: return "rd";
                default: return "th";
                }
            };

            const ordinalSuffix = getOrdinalSuffix(day);
            return `${day}<sup>${ordinalSuffix}</sup> day of ${month} ${year}`;
        },



        Content() {
            const current_date = this.getFormattedDate();
            const budget_in_words = this.numberToWords(this.data.pap_codes[0].pap_code.allocated_budget);
            const rfq_date = this.rfq_date;
            // Filter only awarded suppliers
            // const awardedBids = this.bids.filter(bid => 
            //     bid.bid_details.some(detail => detail.status_id == 9)
            // );

            // Generate a comma-separated list of awarded supplier names
            // const awardedSupplierNames = awardedBids.map(bid => bid.supplier.name).join(", ");
            // const bidsPrice = awardedBids.map(bid => bid.bid_unit_cost).join(", ");

            // const allBids = this.bids;

             // Generate a comma-separated list of not awarded supplier names
            //  const allPRSupplierNames = allBids.map(bid => bid.supplier.name).join(", ");

            // purchase date format
            const prDate = new Date(this.data.purchase_request_date).toLocaleDateString('en-GB', {
                day: '2-digit',
                month: 'long',
                year: 'numeric'
            });

            // Function to convert numbers to Roman numerals
            function toRoman(num) {
                const romanMap = [
                    { value: 1000, numeral: "M" },
                    { value: 900, numeral: "CM" },
                    { value: 500, numeral: "D" },
                    { value: 400, numeral: "CD" },
                    { value: 100, numeral: "C" },
                    { value: 90, numeral: "XC" },
                    { value: 50, numeral: "L" },
                    { value: 40, numeral: "XL" },
                    { value: 10, numeral: "X" },
                    { value: 9, numeral: "IX" },
                    { value: 5, numeral: "V" },
                    { value: 4, numeral: "IV" },
                    { value: 1, numeral: "I" }
                ];
                
                let result = "";
                for (const { value, numeral } of romanMap) {
                    while (num >= value) {
                        result += numeral;
                        num -= value;
                    }
                }
                return result;
            }

            let counter = 2; // Start from II (2)

            // const awardedBidsList = awardedBids.map(bid => {
            //     // Filter bid details where status_id === 13
            //     const filteredBidDetails = bid.bids_details.filter(detail => detail.status_id === 13);

            //     // Map over filtered bid details and generate HTML
            //     const bidDetailsList = filteredBidDetails.map(detail => `
            //         <li style="text-align: justify">
            //             <b>${toRoman(counter++)}.</b> To recommend to the Head of Department of Science and Technology
            //             Regional Office No. IX for his consideration and approval of the award 
            //             of contract for the procurement <b>"${this.data.purchase_request_title.toUpperCase()}"</b>
            //             to the Single Calculated and Responsive Bid of <b>${bid.supplier.name}</b>
            //             with the contract amount of <b>Php ${Number(detail.bids_price).toLocaleString()}</b> only.
            //         </li>
            //     `).join(""); // Join filtered bid details into a string

            //     return bidDetailsList; // Return the combined bid details for this supplier
            // }).join(""); // Joins all suppliers' bid details into one string


            this.editorData = `
                 <div style="margin: 100px 90px 50px 90px; font-size: 16px; font-width: bold">
                        <p style="text-align: center; justify-content:center; align-items:center">
                            <b>
                                RECOMMENDING AWARD OF CONTRACT TO LINES PRINTING SERVICES,  
                                AS THE SINGLE CALCULATED AND RESPONSIVE BID FOR THE PROCUREMENT  
                                "${ this.data.purchase_request_title.toUpperCase() }" UNDERTAKEN  
                                THROUGH SECTION 53.9  
                                (${ this.data.pap_codes[0].pap_code.mode_of_procurement.mode.toUpperCase() })  
                                OF THE REVISED IMPLEMENTING RULES AND REGULATIONS OF R.A. 9184
                            </b>
                        </p>
                        <p style="text-align: justify">
                        <b> WHEREAS</b>, the Regional Director, Mr. Martin A. Wee, approved the DOST-IX Annual Procurement Plan for CY${new Date().getFullYear()}. upon favorable recommendation of the Bids and Awards Committee;
                        </p>
                        <p style="text-align: justify">
                            <b>WHEREAS</b>, the Annual Procurement Plan (Annex "A") contains the procurement 
                            <i style="font-size:12px">"${ this.data.purchase_request_title.toUpperCase() }"</i>
                            with allocated budget of ${budget_in_words} (PHP ${Number(this.data.pap_codes[0].pap_code.allocated_budget).toLocaleString()}),
                            to be procured through Section 53.9 of the revised Implementing Rules and 
                            Regulations (IRR) of the Republic Act (RA) 9184;
                        </p>

                        <p style="text-align: justify">
                            <b>WHEREAS</b>, the BAC has duly received an approved purchase request for the procurement titled 
                            "${ this.data.purchase_request_title.toUpperCase() }" to be bid per item. Detailed technical 
                            specifications pertaining to this procurement are meticulously outlined in 
                            PR no. ${this.data.purchase_request_number} dated ${prDate} (refer to Annex "B");
                        </p>

                        <p style="text-align: justify">
                            <b>WHEREAS</b>, Bids and Awards Committee (BAC) has diligently initiated the procurement 
                            process for the aforementioned project and ensured strict adherence to the provisions of 
                            Republic Act No. 9184 and its Implementing Rules and Regulations;
                        </p>

                    <p style="text-align: justify">
                        <b> WHEREAS</b>, the BAC initiated the procurement through its secretariat through dissemination 
                            of the request for quotation to at least four suppliers of known qualifications in 
                            Zamboanga City to wit: ${allPRSupplierNames};
                    </p>
                        <p style="text-align: justify">
                            <b>WHEREAS</b>, among the above-mentioned bidders, ${awardedSupplierNames} responded by submitting
                            its price quotation to the BAC before opening of bids on ${rfq_date}.
                        </p>

                        <p style="text-align: justify">
                            <b>WHEREAS</b>, the BAC opened its bid document and carefully evaluated its eligibility and technical document. 
                            As a result, the BAC determined its documents as "passed" in complying with all the eligibility and technical requirements;
                        </p>

                        <p style="text-align: justify">
                            <b>WHEREAS</b>, the BAC examined the bid price of the above mentioned bidder. As a 
                            result, the BAC determined that its bid is within the approved budget for bidding, 
                            consequently determined as Single Calculated bid;
                        </p>

                        <p style="text-align: justify">
                        <b>WHEREAS</b>, after verification, validation, and ascertainment of all the statement and 
                        documents submitted by the above mentioned bidder, the BAC determined its 
                        submitted document in order and passed the criteria for post qualificaton;
                        </p>

                        <p style="text-align: justify">
                            <b>NOW, THEREFORE,</b> We the members of the Bids and Awards Committee, by 
                            virtue of the powers vested on Us by the Law, hereby RESOLVE as it hereby 
                            RESOLVED;
                        </p>
                        <p style="text-align: justify; margin-top:-20px">
                            <ul style="list-style-type: none;">
                                    <li style="text-align: justify">
                                        <b>I.</b> To declare ${awardedSupplierNames} as Single Calculated and 
                                        Responsive Bidder of the procurement for <b>""${ this.data.purchase_request_title.toUpperCase() }"</b>
                                    </li>
                                    ${awardedBidsList} 
                                    <br>
                            </ul>
                        </p>

                        <p style="text-align: justify">
                            <b>RESOLVED</b>, at the Department of Science and Technology Regional Office IX,
                            Pettit Barracks, Zamboanga City this ${current_date},
                        </p>
                    </div>
                `;

        },

        submit(){
            this.form.post('/faims/bac-resolutions');
            this.hide();
        }
       
    }
}
</script>